### ISSUE TITLE
非正常停止应用(比如kill -9 )重启应用后，addNameSpace会报错

### ISSUE THREAD

**Issue by ToadKingJiang** [SimonAlong/Butterfly#5]
2021-05-11 11:28:54.871 ERROR [                                ]- [main] c.s.n.Neo : [Neo] sql=> select max(work_id) from butterfly_uuid_generator where namespace = ? for update, parameters => [CustomerManage]
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1837)
	at com.simonalong.neo.TableMap.put(TableMap.java:383)
	at com.simonalong.neo.TableMap.put(TableMap.java:370)
	at com.simonalong.neo.Neo.generateResult(Neo.java:2218)
	at com.simonalong.neo.Neo.executeOne(Neo.java:2183)
	at com.simonalong.neo.Neo.execute(Neo.java:1746)
	at com.simonalong.neo.Neo.exeValue(Neo.java:798)
	at com.simonalong.butterfly.worker.db.DbWorkerIdHandler.lambda$insertWorker$2(DbWorkerIdHandler.java:201)
	at com.simonalong.neo.Neo.tx(Neo.java:1618)
	at com.simonalong.neo.Neo.tx(Neo.java:1525)

数据库内之前add的namespace依然存在，删除后才不报错

**Comment by SimonAlong** [comment]
1. 我这边试了下，即使非正常停止，这个没有删除，再启动也没有问题，1.0.0、1.0.1、1.0.2版本都试了下，没有发现，问下。
2. 还有就是，这个namespace存在其实没啥问题，里面有个“上次更新字段时间戳”，如果没有清理，下次申请时候会检查过期字段，如果过期了会将该过期的分配给新的。

对于这个问题，我问下，你这边的数据库是mysql么，是的话，mysql版本是多少

**Comment by ToadKingJiang** [comment]
> 1. 我这边试了下，即使非正常停止，这个没有删除，再启动也没有问题，1.0.0、1.0.1、1.0.2版本都试了下，没有发现，问下。
> 2. 还有就是，这个namespace存在其实没啥问题，里面有个“上次更新字段时间戳”，如果没有清理，下次申请时候会检查过期字段，如果过期了会将该过期的分配给新的。
> 
> 对于这个问题，我问下，你这边的数据库是mysql么，是的话，mysql版本是多少

你好，是mysql，版本是5.6.31-77.0

**Comment by SimonAlong** [comment]
我这边调用的是jdbc的底层api，这个api的这几个字段都是有驱动填充的，一般不会不存在，你们这边有用什么数据库中间件么，还有就是你说这边还有成功的情况？成功情况下，这个tableName能获取到么？

**Comment by SimonAlong** [comment]
> > 我这边调用的是jdbc的底层api，这个api的这几个字段都是有驱动填充的，一般不会不存在，你们这边有用什么数据库中间件么，还有就是你说这边还有成功的情况？成功情况下，这个tableName能获取到么？
> 
> 如果把那个表数据删了 再addNameSpace是ok的，也是能拿到tableName的

我这边发现问题了，这个是mysql-connect-java驱动层有问题，version >= 8.0.17就没有问题了

问题是这样：
当这个列是函数：max(work_id）这种时候，在8.0.17之前，这个对应的列对应的元数据（metaData）里面tableName为null，算是个问题，在8.0.17版本之后，我测试了下，他们返回不是null了是空字符

解决方式有两个：
1. 升级mysql-connect-java
2. 我这边底层Orm框架兼容下mysql以前的版本下

目前方式1，业务方可以暂时这样用，后续底层框架Neo修改下，然后也将Butterfly也发布下
